-- Fix timetable_slots UNIQUE constraint issue
-- Problem: Only one slot was being stored due to incorrect UNIQUE constraint
-- Solution: Add correct composite unique constraint on (timetable_id, day, start_time)

-- First, let's drop any existing unique constraint on just timetable_id or faculty_id
-- These are too restrictive and cause only one slot to be stored

-- Drop unique constraint on timetable_id if it exists (auto-generated by Sequelize)
ALTER TABLE timetable_slots DROP INDEX IF EXISTS timetable_slots_timetable_id_unique;

-- Drop unique constraint on faculty_id if it exists
ALTER TABLE timetable_slots DROP INDEX IF EXISTS timetable_slots_faculty_id_unique;

-- Add correct composite unique constraint: allows multiple periods per timetable per day/time
-- but prevents duplicate entries for same timetable + day + start_time
ALTER TABLE timetable_slots 
ADD CONSTRAINT uk_timetable_slots_timetable_day_time 
UNIQUE (timetable_id, day, start_time);

-- Verify the constraints are set up correctly
SHOW INDEX FROM timetable_slots WHERE Non_unique = 0;
